# yaml-language-server: $schema=https://raw.githubusercontent.com/runkids/skillshare/main/schemas/config.schema.json
source: /Users/qintianxing/.config/skillshare/skills
extras_source: /Users/qintianxing/.config/skillshare/extras
mode: copy
targets:
  claude:
    skills:
      path: /Users/qintianxing/.claude/skills
  cline:
    skills:
      path: /Users/qintianxing/.agents/skills
  codex:
    skills:
      path: /Users/qintianxing/.codex/skills
  copilot:
    skills:
      path: /Users/qintianxing/.copilot/skills
  cursor:
    skills:
      path: /Users/qintianxing/.cursor/skills
  dexto:
    skills:
      path: /Users/qintianxing/.agents/skills
  openclaw:
    skills:
      path: /Users/qintianxing/.openclaw/skills
  trae:
    skills:
      path: /Users/qintianxing/.trae/skills
  trae-cn:
    skills:
      path: /Users/qintianxing/.trae-cn/skills
  universal:
    skills:
      path: /Users/qintianxing/.agents/skills
  warp:
    skills:
      path: /Users/qintianxing/.agents/skills
  witsy:
    skills:
      path: /Users/qintianxing/.agents/skills
ignore:
  - '**/.DS_Store'
  - '**/.git/**'
audit:
  block_threshold: CRITICAL
